[package]
name = "disruptor-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["rt-multi-thread"] }
async-executor = { version = "1.13.1" }

[dev-dependencies]
criterion = "0.5.1"
